### ISSUE TITLE
When I use tf.keras.models.load_model() method, there is a unexcepted error, ValueError: Unknown layer: BertModelLayer

### ISSUE THREAD

**Issue by fakerbrother** [kpe/bert-for-tf2#48]
hi, I use `model.save()` method to save my model and I create model by functional, but when I use `tf.keras.models.load_model()` method, there is a unexpected error, 
`ValueError: Unknown layer: BertModelLayer`

So, does keras not support custom layer to load? What's more, I must use `model.save_weights()` method? Thanks for your help! Best wishes!

**Comment by kpe** [comment]
@fakerbrother - I guess you might have to provide the `custom_objects` argument, i.e.
```
tf.keras.models.load_model(path, custom_objects={"BertModelLayer": bert.BertModelLayer})
```
check https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects

**Comment by ptamas88** [comment]
Hello,
I saved the model in h5 format with the following code
`model.save('bert_finetuned.h5', save_format='h5')`
Then try to load it with the recommended settings:
`model_2 = tf.keras.models.load_model('bert_finetuned.h5', custom_objects={"BertModelLayer": bert.model.BertModelLayer})`
I get the following error:
```
.../venv/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1113     """
   1114     if not self.is_compatible_with(other):
-> 1115       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1116 
   1117   def most_specific_compatible_shape(self, other):

ValueError: Shapes (119547, 768) and (768, 768) are incompatible
```
I think it's because I use the bert tokenizer vocab (the 119547 size refers to it). How to handle this?
Here is the model architecture:
```
bert_params = bert_tf2.params_from_pretrained_ckpt('multi_cased_L-12_H-768_A-12')
bert_layer = bert_tf2.BertModelLayer.from_params(bert_params, name="bert")
input = tf.keras.layers.Input(shape=(200))
output = bert_layer(input)
output = tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(units=len(tag2idx), activation='softmax'))(output)
model = tf.keras.models.Model(inputs=input, outputs=output)
```
